@startuml

class Tournament
class TournamentTeam
class Match
class MatchByTime
class MatchByScore
class MatchProgram
class MatchResult
class Sport
class KnockOutTournament
class GroupTournament
class Group

class Team
class Player

Team o-- Player
Match <|-- MatchByScore
Match <|-- MatchByTime

Tournament o-- Sport
Tournament <|-- KnockOutTournament
Tournament <|-- GroupTournament
Match o-- MatchResult
MatchProgram o-- Match
Group o-- TournamentTeam
GroupTournament o-- Group
TournamentTeam o-- Team
KnockOutTournament o-- Team

KnockOutTournament o-- MatchProgram
GroupTournament o-- MatchProgram

@enduml